-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cargos
(
    id serial NOT NULL,
    descricao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cargos_pkey PRIMARY KEY (id),
    CONSTRAINT cargos_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cpf character(11) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(11) COLLATE pg_catalog."default" NOT NULL,
    endereco_id integer NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clientes_pkey PRIMARY KEY (id),
    CONSTRAINT clientes_cpf_key UNIQUE (cpf),
    CONSTRAINT clientes_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.enderecos
(
    id serial NOT NULL,
    cep character varying(8) COLLATE pg_catalog."default" NOT NULL,
    logradouro character varying(100) COLLATE pg_catalog."default" NOT NULL,
    num character varying(10) COLLATE pg_catalog."default" NOT NULL,
    bairro character varying(30) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(30) COLLATE pg_catalog."default" NOT NULL,
    uf character(2) COLLATE pg_catalog."default" NOT NULL,
    complemento character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT enderecos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.equipamentos
(
    id serial NOT NULL,
    cliente_id integer NOT NULL,
    tipo_id integer NOT NULL,
    marca_id integer NOT NULL,
    cor character varying(15) COLLATE pg_catalog."default",
    tamanho character varying(20) COLLATE pg_catalog."default",
    ano character(4) COLLATE pg_catalog."default",
    serie character varying(15) COLLATE pg_catalog."default" NOT NULL,
    observacao character varying(255) COLLATE pg_catalog."default",
    criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT equipamentos_pkey PRIMARY KEY (id),
    CONSTRAINT equipamentos_serie_key UNIQUE (serie)
);

CREATE TABLE IF NOT EXISTS public.funcionarios
(
    id serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cpf character(11) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(11) COLLATE pg_catalog."default" NOT NULL,
    endereco_id integer NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cargo_id integer NOT NULL,
    CONSTRAINT funcionarios_pkey PRIMARY KEY (id),
    CONSTRAINT funcionarios_cpf_key UNIQUE (cpf),
    CONSTRAINT funcionarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.marcas
(
    id serial NOT NULL,
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT marcas_pkey PRIMARY KEY (id),
    CONSTRAINT marcas_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS public.ordem_servico
(
    id serial NOT NULL,
    cliente_id integer NOT NULL,
    status_id smallint NOT NULL DEFAULT 1,
    funcionario_id integer,
    data_entrada timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_saida timestamp without time zone,
    CONSTRAINT ordem_servico_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.status
(
    id serial NOT NULL,
    descricao character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT status_pkey PRIMARY KEY (id),
    CONSTRAINT status_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS public.tipos
(
    id serial NOT NULL,
    descricao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipos_pkey PRIMARY KEY (id),
    CONSTRAINT tipos_descricao_key UNIQUE (descricao)
);

ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT clientes_endereco_id_fkey FOREIGN KEY (endereco_id)
    REFERENCES public.enderecos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.equipamentos
    ADD CONSTRAINT equipamentos_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.equipamentos
    ADD CONSTRAINT equipamentos_marca_id_fkey FOREIGN KEY (marca_id)
    REFERENCES public.marcas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.equipamentos
    ADD CONSTRAINT equipamentos_tipo_id_fkey FOREIGN KEY (tipo_id)
    REFERENCES public.tipos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.funcionarios
    ADD CONSTRAINT funcionarios_cargo_id_fkey FOREIGN KEY (cargo_id)
    REFERENCES public.cargos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.funcionarios
    ADD CONSTRAINT funcionarios_endereco_id_fkey FOREIGN KEY (endereco_id)
    REFERENCES public.enderecos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordem_servico
    ADD CONSTRAINT ordem_servico_cliente_id_fkey FOREIGN KEY (cliente_id)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ordem_servico
    ADD CONSTRAINT ordem_servico_funcionario_id_fkey FOREIGN KEY (funcionario_id)
    REFERENCES public.funcionarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.ordem_servico
    ADD CONSTRAINT ordem_servico_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.status (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

END;
